# Generated by Django 4.0.3 on 2022-08-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car_category_location_driver_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.CharField(choices=[('Micro', 'Micro'), ('Mini', 'Mini'), ('Prime Sedan', 'Prime Sedan'), ('Prime SUV', 'Prime SUV')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
